db:
  image: postgres:9.4
  ports:
   - "5432"
web:
  image: tonyd256/novproject:latest
  command: yesod devel
  env_file: .env
  environment:
    - HOST=0.0.0.0
    - PGUSER=postgres
    - PGPASS
    - PGHOST=db
    - PGPORT=5432
    - PGDATABASE=postgres
    - PGTESTDATABASE=postgres_test
    - FACEBOOK_APP_ID=577189602429829
    - FACEBOOK_SECRET=c19d1f5496e39312bd090cd70f5dd5c2
    - RESET_PASSWORD_URL=http://localhost:4200/auth/reset/
  stdin_open: true
#  tty: true
  volumes:
   - .:/app
  ports:
   - "3000:3000"
  links:
   - db
