db:
  image: postgres:9.4
  ports:
   - "5432"
web:
  build: .
  command: yesod devel
  environment:
    - LANG=en_US.UTF-8
    - HOST=0.0.0.0
    - PGUSER=postgres
    - PGPASS
    - PGHOST=db
    - PGPORT=5432
    - PGDATABASE=postgres
    - PGTESTDATABASE=postgres_test
    - FACEBOOK_APP_ID=***REMOVED***
    - FACEBOOK_SECRET=***REMOVED***
  stdin_open: true
  volumes:
   - .:/app
  ports:
   - "3000:3000"
  links:
   - db

