# NOTE: These settings can be overridden by environment variables as well, in
# particular:
#
#    PGHOST
#    PGPORT
#    PGUSER
#    PGPASS
#    PGDATABASE

Default: &defaults
  user: novproject
  password: novproject
  host: localhost
  port: 5432
  database: novproject_api
  poolsize: 10

Development:
  <<: *defaults

Testing:
  database: novproject_test
  <<: *defaults

Staging:
  database: novproject_staging
  poolsize: 100
  <<: *defaults

Production:
  database: novproject_production
  poolsize: 100
  <<: *defaults
