Default: &defaults
  user: novproject
  password: novproject
  host: localhost
  port: 5432
  database: novproject_api
  poolsize: 10

Development:
  <<: *defaults

Testing:
  database: novproject_test
  <<: *defaults

Staging:
  database: novproject_staging
  poolsize: 100
  <<: *defaults

Production:
  database: novproject_production
  poolsize: 100
  <<: *defaults
